[tool.ruff]
line-length = 100

[tool.ruff.lint]
select=["ALL"]
extend-ignore=["D"]
ignore=[
    "EM101", "EM102",
    "FA102",
    "FBT001", "FBT002",
    "G004",
    "N812",
    "NPY002",
    "PD901",
    "PLR2004",
    "PLW2901",
    "PT015",
    "RET504",
    "RSE102",
    "RUF003",
    "S101", "S311", "S602",
    "T201",
    "TRY003",
]
